# Generated by Django 2.2 on 2019-04-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='election',
            field=models.ManyToManyField(null=True, to='candidates.Election'),
        ),
    ]
