# Generated by Django 2.2 on 2019-04-28 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20190427_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='election',
            field=models.ManyToManyField(null=True, to='candidates.Election', verbose_name='Elección'),
        ),
        migrations.AlterField(
            model_name='electorallist',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidates.Party', verbose_name='Partido'),
        ),
    ]
