# Generated by Django 2.2 on 2019-04-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20190428_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='election',
        ),
        migrations.AddField(
            model_name='election',
            name='categories',
            field=models.ManyToManyField(null=True, to='candidates.Category', verbose_name='Categorías'),
        ),
    ]
