# Generated by Django 2.2 on 2019-05-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_auto_20190428_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_listless',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sin Lista'),
        ),
    ]
