# Generated by Django 2.2 on 2019-05-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_category_is_listless'),
    ]

    operations = [
        migrations.AddField(
            model_name='electorallist',
            name='current',
            field=models.BooleanField(default=True, verbose_name='Vigente'),
        ),
    ]
