# Generated by Django 2.2 on 2019-05-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_electorallist_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_listless',
            field=models.BooleanField(default=False, verbose_name='Sin Lista'),
        ),
    ]
