# Generated by Django 2.2 on 2019-05-18 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_auto_20190516_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='electorallist',
            name='add_to_best',
            field=models.BooleanField(default=False, help_text='Si está activado este campo, los votos de esta lista sumarizarán en los reportesal partido con mayor cantidad de Votos', verbose_name='Sumariza al Ganador'),
        ),
        migrations.AlterField(
            model_name='electorallist',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidates.Party', verbose_name='Partido'),
        ),
    ]
