# Generated by Django 2.2 on 2019-05-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_auto_20190518_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='electorallist',
            name='head',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Cabecera'),
        ),
    ]
