# Generated by Django 2.2 on 2019-05-31 02:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_auto_20190530_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
