# Generated by Django 2.2 on 2019-07-18 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20190428_0227'),
        ('candidates', '0012_party_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities.City', verbose_name='Ciudad'),
        ),
    ]
