# Generated by Django 2.2 on 2019-07-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_party_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='year',
            field=models.IntegerField(default=2000, verbose_name='Año'),
        ),
    ]
