# Generated by Django 2.2 on 2019-08-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_auto_20190811_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electorallist',
            options={'ordering': ['order', 'name'], 'verbose_name': 'lista', 'verbose_name_plural': 'listas'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['order', 'name'], 'verbose_name': 'partido', 'verbose_name_plural': 'partidos'},
        ),
    ]
