# Generated by Django 2.2 on 2019-08-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_auto_20190811_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_reports',
            field=models.IntegerField(default=0, verbose_name='Orden en Reportes'),
        ),
    ]
