# Generated by Django 2.2 on 2019-04-26 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Fecha Creación')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categoría', to='candidates.Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='election_vote', to='candidates.Election')),
                ('electoral_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lista', to='candidates.ElectoralList')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mesa', to='places.Table')),
            ],
            options={
                'verbose_name': 'voto',
                'verbose_name_plural': 'votos',
            },
        ),
    ]
