# Generated by Django 2.2 on 2019-04-28 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Total de Votos',
                'verbose_name_plural': 'Totales de Votos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voto.voto',),
        ),
        migrations.AlterField(
            model_name='voto',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidates.Category', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidates.Election', verbose_name='elección'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='electoral_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidates.ElectoralList', verbose_name='lista'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.Table', verbose_name='mesa'),
        ),
    ]
