# Generated by Django 2.2 on 2019-04-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voto', '0002_auto_20190428_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voto',
            options={'permissions': (('can_read_assigned_schools', 'Solo puede leer escuelas que le están asignadas'),), 'verbose_name': 'voto', 'verbose_name_plural': 'votos'},
        ),
    ]
