# Generated by Django 2.2 on 2019-05-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voto', '0003_auto_20190429_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Category', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Election', verbose_name='elección'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='electoral_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.ElectoralList', verbose_name='lista'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Table', verbose_name='mesa'),
        ),
    ]
