# Generated by Django 2.2 on 2019-05-31 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voto', '0005_auto_20190530_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoCharge',
            fields=[
            ],
            options={
                'verbose_name': 'Control de Carga de Votos',
                'verbose_name_plural': 'Control de Carga de Votos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voto.voto',),
        ),
    ]
