# Generated by Django 2.2 on 2019-07-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voto', '0006_votocharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoGraphs',
            fields=[
            ],
            options={
                'verbose_name': 'Gráficos Resultados por Elección',
                'verbose_name_plural': 'Gráficos Resultados por Elección',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voto.voto',),
        ),
    ]
