# Generated by Django 2.2 on 2019-08-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voto', '0007_votographs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votographs',
            options={'verbose_name': 'Resultados en Gráficos', 'verbose_name_plural': 'Resultados en Gráficos'},
        ),
    ]
