# Generated by Django 2.2 on 2019-10-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voto', '0008_auto_20190811_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoStats',
            fields=[
            ],
            options={
                'verbose_name': 'Resultados al AIRE',
                'verbose_name_plural': 'Resultados al AIRE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voto.voto',),
        ),
    ]
