# Generated by Django 2.2 on 2019-04-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cities.Department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='department',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cities.Province', verbose_name='Provincia'),
        ),
    ]
