# Generated by Django 2.2 on 2019-04-26 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Escuela')),
                ('address', models.CharField(max_length=80, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'escuela',
                'verbose_name_plural': 'escuelas',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='escuela', to='places.School')),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
            },
        ),
    ]
