# Generated by Django 2.2 on 2019-04-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'mesa', 'verbose_name_plural': 'mesas'},
        ),
    ]
