# Generated by Django 2.2 on 2019-04-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('places', '0002_auto_20190427_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities.City'),
        ),
        migrations.AddField(
            model_name='table',
            name='elctors_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Electores'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
