# Generated by Django 2.2 on 2019-04-28 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20190427_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities.City', verbose_name='Ciudad'),
        ),
    ]
