# Generated by Django 2.2 on 2019-05-29 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0007_table_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='school',
            name='assigned_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Asignada a'),
        ),
    ]
