# Generated by Django 2.2 on 2019-05-29 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0008_auto_20190528_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_by', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada por '),
        ),
        migrations.AddField(
            model_name='table',
            name='reopen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reopen_by', to=settings.AUTH_USER_MODEL, verbose_name='Re abierta por '),
        ),
    ]
