# Generated by Django 2.2 on 2019-05-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20190528_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Número'),
        ),
    ]
