# Generated by Django 2.2 on 2019-07-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20190530_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['name'], 'verbose_name': 'mesa', 'verbose_name_plural': 'mesas'},
        ),
    ]
