# Generated by Django 2.2 on 2019-08-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_category_order'),
        ('places', '0011_auto_20190718_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='election',
            field=models.ManyToManyField(to='candidates.Election', verbose_name='Elección'),
        ),
    ]
