# Generated by Django 2.2 on 2019-10-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_table_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='gmap_location',
            field=models.URLField(blank=True, null=True, verbose_name='Ubicación'),
        ),
    ]
